name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: backend/requirements.txt
    - name: Install dependencies
      working-directory: ./backend
      run: |
        pip install -r requirements.txt
        pip install -r ../requirements-dev.txt
    - name: Run backend tests
      working-directory: ./backend
      run: |
        python manage.py test --settings=config.settings_test

  bot-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: bot/requirements.txt
    - name: Install dependencies
      run: |
        pip install -r bot/requirements.txt
        pip install -r requirements-dev.txt
    - name: Run bot tests
      working-directory: ./bot
      run: |
        export PYTHONPATH=$PWD
        pytest -W ignore::DeprecationWarning tests/

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        pip install -r backend/requirements.txt
        pip install -r bot/requirements.txt
        pip install -r requirements-dev.txt
        pip install flake8 black isort django-stubs djangorestframework-stubs types-requests
    - name: Run Black
      run: black --check . --exclude="migrations|venv|env|.venv"
    - name: Run isort
      run: isort --profile black --check-only . --skip migrations --skip venv --skip env --skip .venv
    - name: Run flake8
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Run mypy (Backend)
      working-directory: ./backend
      run: |
        export PYTHONPATH=$PWD
        mypy .
